### ISSUE TITLE
Fit tail hyperbola parameters as f(beta, xi)

### ISSUE THREAD

**Issue by deprecated** [deprecated/bowshock-shape#37]
## Tasks for Jorge

- [x] Fit quadratic to x0/beta**-0.55 as function of log beta for different xi
- [x] Fit linear (or quadratic?) to x0 - a as function of log beta for different xi
- [x] Fit the results as f(xi) for some simple form f

## New tasks for Friday

- [x] Check the Level 2 fits for isotropic case (not included in Jorge's new graph)
- [x] Redo the Level 3 fits to obtain the final coefficients
- [x] (*For Will*) Re-check that the Level 1 fits are OK, using the new analytic values

## Methodology

- Use `numpy.polyfit`

**Comment by Lxndrs** [comment]
Check last commit

**Comment by deprecated** [comment]
The fits didn't quite work for some sets of parameters.

For instance, in the isotropic case with beta = 0.1, the analytic function gives xt = 2.7, whereas it should be 2.5, which is an error of 9%.  

To track this down, Jorge needs to plot the intermediate fits to *x0(beta) / trend* and compare them with the real values, as plotted by `conic-tail-fit-vs-beta.py`

**Comment by deprecated** [comment]
![conic-tail-fit-vs-beta](https://cloud.githubusercontent.com/assets/161264/22122340/2a8579b8-de4d-11e6-8940-f309959868f2.jpg)

Part of the problem was that I was using too small a range in beta for the graph.  Here is the corrected version.  It is now obvious that we need a parabola to fit the (x0 - a) curves.

**Comment by Lxndrs** [comment]
Working on issue. I thought that for x0 we may need to fit till 3rd order. 
x0 -a fit was upgraded till 2nd order. 
[fit-tail-params-1.pdf](https://github.com/deprecated/bowshock-shape/files/718106/fit-tail-params-1.pdf)

**Comment by deprecated** [comment]
I am not sure that 3rd order is necessary for the x0 fit.   You can plot the residuals to the fit to see if there is a large scale pattern that might be improved by increasing the order.  But from the graph, it looks like the residuals are of order 0.01, which I think should be good enough.

**Comment by deprecated** [comment]
OK, I see - you already had used 3rd order.  Well that's fine then.   To avoid confusion, I am going to define some terminology:

1. Level 1 fits are fits of hyperbola to the tail for given (beta, xi), giving x0, a
2. Level 2 fits are fits of polynomials to x0 and (x0 - a) as function of beta for each xi
3. Level 3 fits are fits of polynomials to the Level 2 fit coefficients as function of xi

Next tasks: 

- [ ] Check the Level 2 fits for isotropic case (not included in your new graph)
- [ ] Redo the Level 3 fits to obtain the final coefficients
- [ ] (*For Will*) Re-check that the Level 1 fits are OK, using the new analytic values

**Comment by Lxndrs** [comment]
Now the coefficients are saved in astropy tables. From higher order coefficients at the top

**Comment by deprecated** [comment]
I have redone the level 1 hyperbola fits to the tail using the polynomial coefficients from the astropy tables.  This works really well now. 

![conic-head-tail-fit](https://cloud.githubusercontent.com/assets/161264/22179190/ea651188-e011-11e6-9051-df7295769511.jpg)

**Comment by deprecated** [comment]
Resolved in 91592ab
